#Setup

You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A. You buy three
billboards evenly spaced starting on mile marker 17 and ending on mile marker 28. Then you buy another three billboards evenly spaced
starting on mile marker 32 and ending on mile marker 36. In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A.
Determine how far each C" ad is from your restaurant which is located at mile marker 30.

In [1]:
import numpy as np

In [2]:
dist = np.abs(np.linspace([17,32],[28,36],num=3, axis=1,dtype=int)-30) # here we changed default datatype of function np.linspace
dist[[0,1],[2,0]]
#print (dist)

array([2, 2])

#Key Concepts we Used
- (np.linspace) with arrays: Generates interpolations row-wise or column-wise.
- (Broadcasting subtraction): -30 applies to all elements.
- (np.abs): Elementwise absolute value.
- (Fancy indexing): [rows],[cols] picks element pairs.


# Typical numpy.linspace index

In [3]:
np.linspace(start=0,stop=10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# nump.linespace with parameters of array

In [4]:
np.linspace(start=[0,5],stop=[10,15],num=5)

array([[ 0. ,  5. ],
       [ 2.5,  7.5],
       [ 5. , 10. ],
       [ 7.5, 12.5],
       [10. , 15. ]])

# numpy.linspace with axis

In [ ]:
# Step one
dist = np.linspace([17,32],[28,36],num=3, axis=1)
print(dist)

In [ ]:
# Step two
dist = np.linspace([17,32],[28,36],num=3, axis=1)-30
print(dist)

In [ ]:
# Step three
dist = np.abs(np.linspace([17,32],[28,36],num=3, axis=1)-30)
print(dist)

In [ ]:
# Step four
dist = np.abs(np.linspace([17,32],[28,36],num=3, axis=1,dtype=int)-30)
dist[[0,1],[2,0]]