In [2]:
import numpy as np

In [3]:
num = np.array([10,20,30,40,50,60])
print(num)


[10 20 30 40 50 60]


index:0 1 2 3 4 5

# To print the value in index position '4'

In [4]:
print (num[4])

50


# To modify an element in a specific index

In [5]:
num[3]=80
print(num)

[10 20 30 80 50 60]


# Negative indexing
-> It starts from -1 and it represents last value of an array

In [6]:
print(num[-1])
""" We are asking to print the value at -1 index
witch gives the last value of array num[] and output is 60"""

60


' We are asking to print the value at -1 index\nwitch gives the last value of array num[] and output is 60'

Getting the array elements by giving the list of indices

In [7]:
num[[2,4,3]]

array([30, 50, 80])

In [8]:
num[np.zeros(shape=4,dtype='int64')]

array([10, 10, 10, 10])

#Slicing of an array
->arr[start index: end index : step size]


In [9]:
num[0:5:2]
# Slicing an array num with a starting index of 0, ending index of 5 and with step of 2

array([10, 30, 50])

In [10]:
num[2:]  #num = np.array([10 20 30 80 50 60])
# [2:]->gives the valus from index '2'

array([30, 80, 50, 60])

In [11]:
num[:2]  #num = np.array([10 20 30 80 50 60])
# [:2]-> gives the valus before index 2

array([10, 20])

In [12]:
num[::2]  #num = np.array([10 20 30 80 50 60])
#[::2]-> gives all values in an array with step 2

array([10, 30, 50])

# Updating a group list of indices in an array
->The list of values needs to be he same as list of indices

In [23]:
num[[0,1,2,3]] = [100,200,300,400] #list of values it
print(num)             # needs to be same as list of indices


[100 200 300 400  50  60]


In [24]:
# to assign one value to multiple indices, one value to multiple indices we use
num[[0,1]] = 500
print(num)

[500 500 300 400  50  60]
