In [ ]:
import numpy as np

# Printing a Twodimensional array

In [ ]:
bar = np.array([
    [5,10,15,20],
    [25,30,35,40],
    [45,50,55,60]
])
print(bar)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


#Multidimensional arrays have axes to access the elements

1.>axis0 (To access rows)

2.>axis1 (To access Colome's)

                axis1
           (0)  (1) (2) (3)  
      (0)[ [5   10  15  20]
axis0 (1) [25   30  35  40]
      (2) [45   55  32  41] ]


In [ ]:
bar[0,None]

array([[ 5, 10, 15, 20]])

# Slicing for Row

In [ ]:
bar[:1] # it tells array to give me every thing upto excluding "1"

array([[ 5, 10, 15, 20]])

In [ ]:
bar[1:3,[-2,-1]]
'''It tells array to give me the valus
 between rows one and three (three exclusive)and the second
to last column and last column'''


'It tells array to give me the valus\n between rows one and three (three exclusive)and the second\nto last column and last column'

# Modifying the Twodimensional array

In [ ]:
bar[0,0]=-1
print (bar)  # hear we replaced first element with -1

[[-1 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [ ]:
bar[1]=bar[2]
print(bar) # hear we replaced second row with third row

[[-1 10 15 20]
 [45 50 55 60]
 [45 50 55 60]]


In [ ]:
bar [[0,1,2],[0,1,2]]=[0,0,0]
print (bar)

[[ 0 10 15 20]
 [45  0 55 60]
 [45 50  0 60]]


#Printing a threedimentional array

In [39]:
zoo= np.array([
    [
       [10,20],
       [30,40],
       [50,60],
    ],
    [
[11,12],
    [13,14],
    [15,16]
    ]
])

In [40]:
print (zoo)

[[[10 20]
  [30 40]
  [50 60]]

 [[11 12]
  [13 14]
  [15 16]]]


In [45]:
zoo [:2,:,1]

array([[20, 40, 60],
       [12, 14, 16]])