In [2]:
price = []
n= 60*60*24*365
for i in range(n):
    price.append(100+i/100)
print (price[:5])

[100.0, 100.01, 100.02, 100.03, 100.04]


In [3]:
avg = 0.0
for p in price:
  avg += p/len(price)
print (avg)

157779.995


**The Python loops are more time-consuming, and the number of iterations are high in comparison to numpy**

In [13]:
import numpy as jay

In [14]:
price   =100 + jay.arange(n)/100
print (price[:2])

[100.   100.01]


In [15]:
avg = jay.mean (price)
print (avg)

157779.995


In [17]:
arr = jay. array([10,20,30,40,50,60,70,80,90])

In [18]:
print(arr)

[10 20 30 40 50 60 70 80 90]


In [19]:
arr.ndim

1

The .ndim attribute returns the number of dimensions, or axes, of the array. In this case, since arr is a 1-dimensional array, the output will be 1

In [20]:
arr.shape

(9,)

arr.shape is accessing the shape attribute of the NumPy array arr. The shape attribute returns a tuple representing the dimensions of the array. For arr, which is a 1-dimensional array with 9 elements, the output will be (9,).

In [23]:
arr_2d = jay.array([[10,20,30,40,50],[100,200,300,400,500]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(len(arr_2d))


[[ 10  20  30  40  50]
 [100 200 300 400 500]]
2
(2, 5)
2


In [24]:
type(arr_2d)

numpy.ndarray

In [27]:
arr_2d.dtype

dtype('int64')

# Rules for numpy Arrays
1. Every element in the array must be of the same type and size.
2. If an array's elements are also arrays, those inner arrays must have the same type and number of elements as each other.



# An array of a list

In [28]:
jay.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

# Array from a list of lists

In [31]:
jay.array([[['a','b'],['c','d']],
          [['e','f'],['g','h']]])

array([[['a', 'b'],
        ['c', 'd']],

       [['e', 'f'],
        ['g', 'h']]], dtype='<U1')

# A three-dimensional array from a list of lists

In [32]:
# A three-dimensional array from a list of lists
jay.array([[['a','b','c'],['d','e','f'],['g','h','i']]])

array([[['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']]], dtype='<U1')

# Numpy.Zeros
Numpy.Zeros - Returns a new array of given shape , filled with zeros

In [36]:
jay.zeros(shape=(3,5))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Numpy.full
numpy.full-returns a new array of given shape and type, filled with fill_value

In [41]:
jay.full(shape=(3,5),fill_value='jay')

array([['jay', 'jay', 'jay', 'jay', 'jay'],
       ['jay', 'jay', 'jay', 'jay', 'jay'],
       ['jay', 'jay', 'jay', 'jay', 'jay']], dtype='<U3')

#numpy.arange
numpay.arange- Return evenly spaced values within a given interval

In [45]:
x=jay.arange(start=1,stop=5,step=2)
y=jay.arange(20)
print(x)
print(y)

[1 3]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#numpy.random.randint
numpy.random.randint - returns random integers from low to high


In [115]:
x=jay.random.randint(0,22)
print(x)
y=x=jay.random.randint(low=10,high=30)
print(y)


0
12
